language: python
python:
  - "2.7"
before_install:
  - wget https://www.dropbox.com/s/holuoc1v35ecmuo/gtCNV_v1.0_resources.tar.gz
  - tar zxvf gtCNV_v1.0_resources.tar.gz
    # Install bedtools
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.25.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..
install: 
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install numpy scipy pandas scikit-learn pybedtools pysam 
script:
  - python test.py -i tutorial/tutorial.in -b tutorial/tutorial.bed -o test.vcf
