language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --yes --add channels r
  - conda config --yes --add channels bioconda
  - wget https://www.dropbox.com/s/holuoc1v35ecmuo/gtCNV_v1.0_resources.tar.gz
  - tar zxvf gtCNV_v1.0_resources.tar.gz
    # Install bedtools
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.25.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..
install: 
  - conda install --yes numpy scipy pandas scikit-learn pybedtools pysam 
