language: python
python:
  - "2.7"
before_install:
  - wget https://www.dropbox.com/s/holuoc1v35ecmuo/gtCNV_v1.0_resources.tar.gz
  - tar zxvf gtCNV_v1.0_resources.tar.gz
    # Install bedtools
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.25.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..
install: "pip install pysam pybedtools scikit-learn numpy pandas scipy"
